version: '3.4'

services:

  backend:
  # giving location of docker file
    build: ./backend_project  
    ports:
      - 8080:8080

    # needs an environment variable to know where the data base is
    depends_on:
      - database
    environment:
      JDBC_URL: jdbc:postgresql://host.docker.internal:5432/adventure_game
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: adventure_game

  frontend:
  # giving location of docker file
    build: ./frontend_project
    ports:
      - 3000:3000

  database:
  # pulling in an image for the database from docker hub
    image: postgres:15.3
    restart: always
    # based on a port that postgresql listens to
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # kad nereiktu username & password
      POSTGRES_DB: adventure_game
    volumes:
      - ./adventure_game:/var/lib/postgresql/data

volumes:
  adventure_game:

      





  # adventuregamecopy:
  #   image: adventuregamecopy
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8080:8080
