FROM openjdk:17

# RUN mkdir "backend_app"

# COPY . /backend_app

ARG JAVA_OPTS

ENV JAVA_OPTS=$JAVA_OPTS

COPY target/backend_project-0.0.1-SNAPSHOT.jar adventuregamecopy.jar

# WORKDIR /backend_app/src

EXPOSE 8080

ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar adventuregamecopy.jar


